version: "3"
services:
  mongo:
    container_name: user-management-mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: database
    networks:
      - common-net
  backend:
    container_name: user-management-backend
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - common-net

networks:
  common-net:
    driver: bridge
